# Generated by Django 4.0 on 2021-12-30 02:44

from django.db import migrations, models
import djongo.models.fields
import topics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('selectedTopicId', models.CharField(max_length=255)),
                ('topic', djongo.models.fields.ArrayField(model_container=topics.models.Topic)),
            ],
        ),
    ]
