# Generated by Django 4.0 on 2021-12-30 09:31

from django.db import migrations
import djongo.models.fields
import topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='topic',
            field=djongo.models.fields.ArrayField(blank=True, model_container=topics.models.Topic),
        ),
    ]
