# Generated by Django 3.1.12 on 2022-01-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='topic',
            new_name='topics',
        ),
    ]
