# Generated by Django 3.1.12 on 2022-01-05 14:00

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('userId', models.IntegerField()),
                ('uuidToken', models.CharField(default=uuid.UUID('e9b39332-9dd3-4f73-ae72-9fdfcbd06773'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('expDate', models.DateTimeField(default=datetime.datetime(2022, 1, 6, 9, 0, 13, 193784))),
            ],
        ),
    ]
