# Generated by Django 3.1.12 on 2022-01-05 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 11, 38, 6, 834271), editable=False),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='userId',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='uuidToken',
            field=models.CharField(default='6be0f579-055a-44fd-9799-e72914af4a5f', editable=False, max_length=36, unique=True),
        ),
    ]
