# Generated by Django 3.1.12 on 2022-01-05 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220105_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 11, 40, 50, 347619), editable=False),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='uuidToken',
            field=models.CharField(default='1f77a3c2-a179-44f9-a7d6-ede3e0831d37', editable=False, max_length=36, unique=True),
        ),
    ]
